language: node_js
node_js: 
  -"7"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script: 
  - ng build 
install: 
  - npm install -g firebase-tools
after_success: 
  - firebase deploy --project fuerteventura-project --token 1/twCTUzFb59nx3WlolZCZoto-Zful-Xm_LmbgR1YRU4Y